/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { LixirBase, LixirBaseInterface } from "../LixirBase";

const _abi = [
  {
    inputs: [],
    name: "registry",
    outputs: [
      {
        internalType: "contract LixirRegistry",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class LixirBase__factory {
  static readonly abi = _abi;
  static createInterface(): LixirBaseInterface {
    return new utils.Interface(_abi) as LixirBaseInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LixirBase {
    return new Contract(address, _abi, signerOrProvider) as LixirBase;
  }
}
